In [2]:
import sqlite3
conn=sqlite3.connect('student.db')
cursor=conn.cursor()

In [3]:
cursor.execute('''
CREATE TABLE IF NOT EXISTS students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    age INTEGER,
    grade TEXT)
''')
conn.commit()
print("Table created successfully.")

Table created successfully.


In [5]:
def insert(name, age, grade):
    cursor.execute("Insert into students (name, age, grade) values(?, ?, ?)", (name, age, grade))
    conn.commit()
    print("Student inserted successfully.")


insert('Riya', 20, 'A')
insert('Divyank', 22, 'B')

Student inserted successfully.
Student inserted successfully.


In [10]:
def fetch():
    cursor.execute("SELECT * FROM students")
    rows = cursor.fetchall()
    for row in rows:
        print(row)
fetch()

(1, 'Riya', 20, 'A')
(2, 'Divyank', 22, 'B')


In [14]:
def update(id, name, age, grade):
    cursor.execute("update students set name=?, age=?, grade=? WHERE id=?", (name, age, grade, id))
    conn.commit()
    print("Student updated successfully.")
update(1, 'Riya Sharma', 21, 'A+')

Student updated successfully.


In [25]:
def delete(id):
    cursor.execute("delete from students where id=?", (id,))
    conn.commit()
    print("Student deleted successfully.")

delete(2)

Student deleted successfully.


In [ ]:
# cursor.execute('''
# SELECT students.name, marks.subject, marks.marks
# FROM students
# JOIN marks ON students.student_id = marks.student_id
# ''')

# rows = cursor.fetchall()
# for row in rows:
#     print(row)


In [ ]:
conn.close()
print("Database connection closed.")

In [2]:
#NUMPY  (numerical python)
import numpy as np

In [41]:
a=np.array([1,2,3])    #1-D array
b=np.array([[1,2],[3,4]])   #2-D array
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [44]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)   #tell (rows, columns)
print(a.size)    #number of element in the array.
print(a.ndim)    #tell dimension of the array.
print(a.dtype)   #data type of element in the array. 

(2, 3)
6
2
int64


In [45]:
a=np.array([1,2,3,4,5,6])
a.reshape([2,3])

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
print(a[1:4])

[2 3 4]


In [3]:
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.eye(3,3)) #Identity matrix
print(np.full((2,2),7)) #Filled with 7
print(np.arange(1,10,2)) #[1 3 5 7 9]
print(np.linspace(1,5,5)) #[1. 2.33 3.66 5.]

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 7]
 [7 7]]
[1 3 5 7 9]
[1. 2. 3. 4. 5.]


In [50]:
a=np.array([1,2,3])
b=np.array([4,5,6])


print(a+b)
print(a*b)
print(a ** 2)
print(np.sqrt(a))
print(np.mean(a))




[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]
2.0


In [52]:
arr=np.array([[1,2,3],[4,5,6]])

print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))


21
1
6
[5 7 9]
[ 6 15]


In [6]:
arr=np.array([[1,2],[3,4]])
a=arr.flat
for i in a:
    print(i)

1
2
3
4


In [55]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
a=np.array([[1,2],[4,5]])
b=np.array([[1,2],[4,5]])
print

In [ ]:
#PANDAS  (panel data)
import pandas as pd

In [58]:
a=np.zeros(10)
a[4]=1
print(a)

In [62]:
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [63]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
